/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-11-23 21:45:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ar.com.integrador.domain.Orador;
import java.util.List;

public final class editar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ar.com.integrador.domain.Orador");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

 Orador orador = (Orador)request.getAttribute("orador"); // levanto el departamento que viene del controller

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("\n");
      out.write("	<head>\n");
      out.write("	  <meta charset=\"utf-8\">\n");
      out.write("	  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("	\n");
      out.write("	  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n");
      out.write("	  <link rel=\"stylesheet\" href=\"css/estilos-propios.css\">\n");
      out.write("	  <link rel=\"shortcut icon\" href=\"./img/codoacodo-min.png\" type=\"image/x-icon\">\n");
      out.write("	\n");
      out.write("	  <title>Trabajo Integrador</title>\n");
      out.write("	  <style>\n");
      out.write("		    body{\n");
      out.write("		        height:100vh;\n");
      out.write("		        display: grid;\n");
      out.write("		        grid-template-rows: 10% 75% 15%;\n");
      out.write("		        grid-template-areas: \"header\"\n");
      out.write("		                             \"main\"\n");
      out.write("		                             \"footer\";  \n");
      out.write("		\n");
      out.write("		    }\n");
      out.write("		    header{\n");
      out.write("		        grid-area: header;\n");
      out.write("		    }\n");
      out.write("		    main{\n");
      out.write("		        grid-area: main;\n");
      out.write("		        overflow: auto;\n");
      out.write("		    }\n");
      out.write("		    footer{\n");
      out.write("		        grid-area: footer;\n");
      out.write("		      \n");
      out.write("		    }\n");
      out.write("		  </style>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("	\n");
      out.write("		<header>\n");
      out.write("		    <nav class=\"navbar navbar-dark bg-dark fixed-top navbar-expand-lg\">\n");
      out.write("		        <div class=\"container\">\n");
      out.write("		            <a class=\"navbar-brand\" href=\"index.jsp\">\n");
      out.write("		                <img src=\"img/codoacodo-min.png\" alt=\"Codo a Codo logo\">\n");
      out.write("		                Conf Bs As\n");
      out.write("		            </a>\n");
      out.write("		            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("		                data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("		                aria-label=\"Toggle navigation\">\n");
      out.write("		                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		            </button>\n");
      out.write("		            <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarSupportedContent\">\n");
      out.write("		                <ul class=\"navbar-nav mb-2 mb-lg-0\">\n");
      out.write("		                    <li class=\"nav-item\">\n");
      out.write("		                        <a class=\"nav-link active\" aria-current=\"page\" href=\"./index.jsp\">La conferencia</a>\n");
      out.write("		                    </li>\n");
      out.write("		                    <li class=\"nav-item\">\n");
      out.write("		                        <a class=\"nav-link\" href=\"./index.jsp#oradores\">Los oradores</a>\n");
      out.write("		                    </li>\n");
      out.write("		                    <li class=\"nav-item\">\n");
      out.write("		                        <a class=\"nav-link\" href=\"./index.jsp#lugar\">El lugar y la fecha</a>\n");
      out.write("		                    </li>\n");
      out.write("		                    <li class=\"nav-item\">\n");
      out.write("		                        <a class=\"nav-link\" href=\"./index.jsp#form-orador\">Conviértete en orador</a>\n");
      out.write("		                    </li>\n");
      out.write("		                    <li class=\"nav-item\">\n");
      out.write("		                        <a class=\"nav-link btn-compra-tickets\" href=\"comprar-tickets.html\">Comprar tickets</a>\n");
      out.write("		                    </li>\n");
      out.write("		                     <li class=\"nav-item\">\n");
      out.write("                        		<a class=\"nav-link\" href=\"login.jsp\">LogIn</a>\n");
      out.write("                    		</li>\n");
      out.write("		                </ul>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		    </nav>\n");
      out.write("		</header>\n");
      out.write("		\n");
      out.write("		<main class=\"mb-5\">\n");
      out.write("          <section class=\"container mt-5\" id=\"form-orador\">\n");
      out.write("		        <div class=\"row justify-content-center\">\n");
      out.write("		            <div class=\"col-lg-8 col-xl-7\">\n");
      out.write("		                <h2 class=\"titulo-gral\">Modificar datos del Orador</h2>\n");
      out.write("		               \n");
      out.write("		                <form action=\"");
      out.print(request.getContextPath());
      out.write("/UpdateOradorController\" method=\"POST\">\n");
      out.write("		                    <div class=\"row gx-2\">\n");
      out.write("		                        <div class=\"col-md mb-3\">\n");
      out.write("		                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(orador.getId());
      out.write("\">\n");
      out.write("		                            <input type=\"text\" class=\"form-control\" \n");
      out.write("		                             name=\"nombre\" \n");
      out.write("		                             placeholder=\"Nombre\" \n");
      out.write("		                             aria-label=\"Nombre\"\n");
      out.write("		                             id=\"validationCustom02\"\n");
      out.write("		                             value=\"");
      out.print(orador.getNombre());
      out.write("\" \n");
      out.write("		                             required>\n");
      out.write("		                        </div>\n");
      out.write("		                        <div class=\"col-md mb-3\">\n");
      out.write("		                            <input type=\"text\" class=\"form-control\" name=\"apellido\" placeholder=\"Apellido\" aria-label=\"Apellido\"\n");
      out.write("		                             value=\"");
      out.print(orador.getApellido());
      out.write("\" \n");
      out.write("		                             required>\n");
      out.write("		                        </div>\n");
      out.write("		                    </div>\n");
      out.write("		                    <div class=\"row\">\n");
      out.write("		                        <div class=\"col mb-3\">\n");
      out.write("		                            <input type=\"email\" class=\"form-control\" name=\"mail\" placeholder=\"Email\" aria-label=\"Email\"\n");
      out.write("		                            value=\"");
      out.print(orador.getMail());
      out.write("\"  \n");
      out.write("		                            required>\n");
      out.write("		                        </div>\n");
      out.write("		                    </div>\n");
      out.write("		                    <div class=\"row\">\n");
      out.write("		                        <div class=\"col mb-3\">\n");
      out.write("		                            <textarea class=\"form-control\" name=\"tema\" id=\"exampleFormControlTextarea1\" rows=\"4\"\n");
      out.write("		                              \n");
      out.write("		                                placeholder=\"");
      out.print(orador.getTema());
      out.write("\" \n");
      out.write("		                                \n");
      out.write("		                                required>");
      out.print(orador.getTema());
      out.write(" </textarea>\n");
      out.write("		                            <div id=\"emailHelp\" class=\"form-text mb-3\">Recuerda incluir un título para tu charla.</div>\n");
      out.write("		                            <div class=\"d-grid\">\n");
      out.write("		                                <button type=\"submit\" class=\"btn btn-lg btn-form\">Modificar</button>\n");
      out.write("		                            </div>\n");
      out.write("		                        </div>\n");
      out.write("		                    </div>\n");
      out.write("		                </form>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		    </section>\n");
      out.write("		\n");
      out.write("		</main>\n");
      out.write("		\n");
      out.write("		<footer id=\"main-footer\">\n");
      out.write("		    <div class=\"container\">\n");
      out.write("		        <ul class=\"nav justify-content-center justify-content-lg-between align-items-center\">\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Preguntas <span>frecuentes</span></a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Contáctanos</a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Prensa</a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Conferencias</a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Términos y <span>condiciones</span></a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Privacidad</a>\n");
      out.write("		            </li>\n");
      out.write("		            <li class=\"nav-item\">\n");
      out.write("		                <a class=\"nav-link\" href=\"#\">Estudiantes</a>\n");
      out.write("		            </li>\n");
      out.write("		        </ul>\n");
      out.write("		    </div>\n");
      out.write("		</footer>\n");
      out.write("		\n");
      out.write("		<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
